baseURL = "/"
languageCode = "en-us"
theme = "hugo-hero-theme"
themesDir = "themes"
title = "Climate-Scale"
[[menu.main]]
name = "Connect"
url = "/contact/"
weight = 4
[[menu.main]]
name = "Why Climate-Scale"
url = "/about/"
weight = 3
[[menu.main]]
name = "Use Cases"
url = "/work/"
weight = 2
[[menu.main]]
name = "Climate Data"
url = "/services/"
weight = 1
[params]
google_analytics_id = ""
[params.homepage_meta_tags]
meta_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and fullwidth sections. It contains content types for a business or portfolio site."
meta_og_description = "Data for climate change analysis"
meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
meta_og_title = "Vortex"
meta_og_type = "website"
meta_og_url = "https://hugo-hero.netlify.com"
meta_twitter_card = "summary"
meta_twitter_creator = "@zerostaticio"
meta_twitter_site = "@zerostaticio"
[permalinks]
pages = "/:filename/"
post = "/:year/:month/:day/:slug/"
